### ISSUE TITLE
Does django guardian support multiple databases?

### ISSUE THREAD

**Issue by shrike71** [django-guardian/django-guardian#288] opened 2015-01-09 14:13 UTC
Hi,

Trying to use the admin interface to apply row-level guardian permissions to groups with an implementation of multiple databases in Django (Django 1.7, Python 3.4, sqlite3). When I DON'T use multiple dbs, the permission application WORKS, however, if I use multiple databases, the permssion assignment (after i allocate the permissions I want for a group and hit 'save')  returns with an error:

OperationalError:
no such table: product

Here's the basic dump:
Request Method: 	POST
Request URL: 	http://vdms:8000/admin/vmanager/product/3/permissions/group-manage/1/
Django Version: 	1.7
Exception Type: 	OperationalError
Exception Value: 	

no such table: product

Exception Location: 	/usr/local/lib/python3.4/dist-packages/django/db/backends/sqlite3/base.py in execute, line 485
Python Executable: 	/usr/bin/python3
Python Version: 	3.4.0
Python Path: 	

['/home/vdms/projects/python/vdms',
 '/usr/local/lib/python3.4/dist-packages/soaplib-2.0.0_beta2-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/Flask_Enterprise-1.0-py3.4.egg',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages']

**Comment by lucasdavid** [comment] 2015-07-30 20:16
Just ran into the same problem. Have you found any workaround, @shrike71?

**Comment by lucasdavid** [comment] 2015-07-31 19:49
In case someone's also facing this issue: debugging, you can clearly see that the problem is actually in `ContentType.get_object_for_this_type` and `ContentType.get_all_objects_for_this_type`.
```py
def get_object_for_this_type(self, **kwargs):
    return self.model_class()._base_manager.using(self._state.db).get(**kwargs)

def get_all_objects_for_this_type(self, **kwargs):
    return self.model_class()._base_manager.using(self._state.db).filter(**kwargs)
```
`ContentType` calls `using()` over the model's manager, switching from its default database to the database that contains the permissions. It then tries to retrieve or filter the collection, which raises the error.

A [discussion about this issue](https://code.djangoproject.com/ticket/16281) has taken place for over 4 years! Anyways, according with it, this issue can be fixed by removing the `using(self._state.db)` call from `_base_manager`.

**Comment by brianmay** [comment] 2015-11-14 00:21
Suggest we document this as a known issue and give a reference to the Django bug. Don't think there is anything else we can do.

**Closed** 2015-12-11 09:30 UTC
Labels: Documentation

**Comment by clover-es** [comment] 2019-02-09 02:10
Hello,

Any news about this happening with Django 2.1? I have though about making a dbRouter for django-guardian, allowing to check in which database is hosted the object being managed, and thus having the django-guardian table created in each database being used.

Any other ideas are welcome. Thank you!

**Comment by bofilio** [comment] 2023-01-11 15:55
django default permissions do not support permissions across multiple databases, due to that foreign keys issue,  guardian use same strategy ( foreign keys ) so I think its the same problem. not supported .

**Comment by DmytroLitvinov** [comment] 2024-04-22 16:38
Just came here from [the documentation point "Using multiple databases"](https://django-guardian.readthedocs.io/en/stable/userguide/caveats.html#using-multiple-databases) and rechecked link to Django issueand seems like [support for multiple database was added 3 months ago](https://code.djangoproject.com/ticket/16281#comment:37) in Django 5.1 version.

**Comment by adnannazir** [comment] 2024-11-03 09:30
Yes the big seems to be fixed, so should it be working fine with multiple databases?
