### ISSUE TITLE
get_objects_for_user with any_perm=True leads to type error in postgres.

### ISSUE THREAD

**Issue by drepo** [django-guardian/django-guardian#366] opened 2015-11-27 05:17 UTC
This, I believe, is related to `object_pk` being a `VARCHAR(255)`, whereas the `id` fields are usually `INT` types in the `UserObjectPermission` model

A sample of query being generated which is failing (at the `"app_model"."id" IN` clause). The query is relatively longer. I am posting only a part of it.

```sql
SELECT <Fields> FROM "report_report"   
WHERE ("app_model"."id" IN (  
      SELECT U0."object_pk" FROM "guardian_userobjectpermission" U0   
     INNER JOIN "auth_permission" U2 ON ( U0."permission_id" = U2."id" )   
     WHERE (U0."user_id" = 11 AND U2."content_type_id" = 10 AND U2."codename" IN (abc, xyz, efg)))
```

Terminal error:
```bash
psycopg2.ProgrammingError: operator does not exist: integer = character varying
LINE 1: ... FROM "app_model" WHERE ("app_model"."id" IN (SELECT...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

Stack:
Django==1.8.7
django-guardian==1.3.2
python==3.4.3
Linux Mint==17.2 (64-bit)
Postgres==9.3.10

**Comment by brianmay** [comment] 2015-12-03 22:29
Sorry, not sure I understand what that query is doing or why Postgresql is getting upset.

It would really help if we could see the stack trace, so we can identify what line of code is producing this error.

Basically the above SQ, simplified is:

```
SELECT <Fields> FROM "report_report"  WHERE ("app_model"."id" IN (<list of strings>))
```

Is Postgresql saying it doesn't like comparing app_model.id with a string?

What is app_model and how does it relate to the report_report? What is content_type 10 on your system?

**Comment by brianmay** [comment] 2015-12-03 22:49
I can see why string is used, I imagine this might be for the case where the id field is not an integer.

In fact, Django code itself does something similar, see the `LogEntry` model in contrib.admin.models.

So I think maybe this might be an upstream Django issue.

**Comment by brianmay** [comment] 2015-12-22 09:54
Not enough information given to work on. It might be a Django issue, however there is not enough information to report to Django either.

**Comment by tomka** [comment] 2015-12-23 23:25
I am experiencing the exact same thing (Postgres error "No operator matches the given name and argument type(s). You might need to add explicit type casts."). I wanted to upgrade django-guardian from v1.2.5. I tested with both Django 1.7.11 and 1.8.7 as well as django-guardian 1.3, 1.3.1 and 1.3.2 to no avail, all trigger the error.

The first query @drepo shows and that you reference with

> Is Postgresql saying it doesn't like comparing app_model.id with a string?

is generated by Django, probably through an ORM request in the ``has_perm`` method of the user model. And yes, Postgres doesn't want to compare integer IDs to strings (generated by the subquery). This is the end of the stack trace:

```
  File "/srv/http/catmaid/django/applications/catmaid/control/project.py", line 77, in get_project_qs_for_user
    return get_objects_for_user(user, perms, Project, any_perm=True)
  File "/home/tom/.virtualenvs/catmaid/lib/python2.7/site-packages/guardian/shortcuts.py", line 416, in get_objects_for_user
    if user.has_perm(app_label + \'.\' + code):
TypeError: unsupported operand type(s) for +: \'NoneType\' and \'unicode\'
', u'error': u"unsupported operand type(s) for +: 'NoneType' and 'unicode'"}
```

And with some context:

```
/home/tom/.virtualenvs/catmaid/lib/python2.7/site-packages/guardian/shortcuts.pyc in get_objects_for_user(user=<User: tom>, perms=['can_administer', 'can_annotate', 'can_browse'], klass=<class 'catmaid.models.Project'>, use_groups=True, any_perm=True, with_superuser=True, accept_global_perms=True)
    414     if accept_global_perms and with_superuser:
    415         for code in codenames:
--> 416             if user.has_perm(app_label + '.' + code):
        user.has_perm = <bound method User.has_perm of <User: tom>>
        app_label = None
        code = 'can_administer'
    417                 global_perms.add(code)
    418         for code in global_perms:

TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'
```

This will trigger the error:

   get_objects_for_user(user, perms, model, any_perm=True)

while `any_perm=False` makes it work. Since the error is raised in Django's user model, this might be a problem in Django.

**Comment by tomka** [comment] 2015-12-23 23:32
Interestingly, if I set `accept_global_perms=False`, this problem goes away. Of course the `user.has_perm()` query above is avoided, but the error also doesn't seem to be triggered from another query.

**Comment by sathoro** [comment] 2015-12-28 23:30
This is an error in version 1.3.2. I downgraded to 1.3.1 and it was immediately resolved. I wish I had time to look into this but hopefully that will help to narrow it down. It occurred using Django 1.8.3 and Postgres 9.4.4 and 9.4.5 when using the `get_objects_for_user` function with or without `accept_global_perms=False`

**Comment by ad-m** [comment] 2015-12-28 23:43
@sathoro , there is 38 commits between v.1.3.2 and v.1.3.1 ( https://github.com/django-guardian/django-guardian/compare/v1.3.1...v1.3.2 ). Do you can use ```git bisect``` ( https://git-scm.com/docs/git-bisect ) to identify wrong commit? Firstly you should install django-guardian locally (eg. ```git clone https://github.com/django-guardian/django-guardian.git django-guardian && ln -s django-guardian/guardian/ guardian```.

**Comment by sathoro** [comment] 2015-12-29 01:58
@ad-m 3cdfd12a8906cc91a386d12bcfdd0f12f527dfb9 appears to be the commit

**Comment by ad-m** [comment] 2015-12-29 02:05
@sathoro, thank you.

**Comment by ad-m** [comment] 2015-12-29 02:13
@mitar, could there to look? Do you have any idea? (I don't know PostgreSQL) @sathoro mention your commit as source of the issue.

**Comment by sathoro** [comment] 2015-12-29 02:31
@ad-m I think that we need to change `object_pk` from a CharField to an IntegerField. The problem is that a join is being created and the join is comparing a primary key (usually an integer field) with the object_pk which is a varchar. Even though it doesn't error out with MySQL, I think it is still a problem because if I remember correctly, joins that use different datatypes can't use indexes so it could lead to slow queries.

**Comment by mitar** [comment] 2015-12-29 08:07
I think there are two things combined here. The `TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'` does not look like PostgreSQL error what was what this ticket about initially, but it is a Python error. I think we should open another ticket for that. I remember that the Python exception mentioned above I was getting before this commit: https://github.com/django-guardian/django-guardian/commit/f9392a5ca9d82422a80719fdfef03a3602d023fb From the code shown above it seems that @tomka does not run the 1.3.2 version? @tomka can you make sure you are running 1.3.2? Because in 1.3.2 the code should be:

```
if user.has_perm(ctype.app_label + '.' + code):
```

and not:

```
if user.has_perm(app_label + '.' + code):
```

As for the PostgreSQL issue, it would be great to know more about the concrete code being run. I have not seen that error before. Also, assuming that IDs are integers is not really a good approach, because this is not necessary so. Maybe that should be a configuration option. Or maybe we could have few different base classes, or an abstract class where developer can specify their ID.

[Django documentation](https://docs.djangoproject.com/en/1.9/ref/contrib/contenttypes/#django.contrib.contenttypes.fields.GenericForeignKey) proposes that this is integer, but does not require to do so.

On other approach would be to allow specifying casting. If you have to mix various types together.

Anyway, it is interesting that nobody else has noticed this PostgreSQL errors? So what is the difference? Because this app was using `CharField` for a long time for `object_pk` for a long time. What is different now?

> I think it is still a problem because if I remember correctly, joins that use different datatypes can't use indexes so it could lead to slow queries.

Do you have some reference for this? For current DBMSs?

cc @kostko

**Comment by sathoro** [comment] 2015-12-29 08:30
@mitar The reason the Postgres errors are coming up now is because before there were two queries. After the first query the object_pks values are cast into integers before being used as input into the second query (probably being cast by Django). However with the code in v1.3.2 there is now a single query with a join that attempts to join the object_pk (varchar) column with my model's id (integer) column.

> Do you have some reference for this? For current DBMSs?

I was actually thinking about character encoding/collation (like an ascii encoded column vs utf8) so it looks like I may have been incorrect about a varchar to integer join being slow.

**Comment by mitar** [comment] 2015-12-29 09:05
Also, see the discussion [here](https://github.com/django-guardian/django-guardian/blob/devel/docs/userguide/performance.rst) about how to use dedicated foreign keys. It seems that current very generic non-integer one is on purpose there, so that it works in all cases, and then you can optimize by introducing dedicated foreign keys.

**Comment by mitar** [comment] 2015-12-29 09:06
@sathoro can you make a simple reproduction for this? Or a test case?

**Comment by brianmay** [comment] 2016-01-06 00:28
The "TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'" error looks suspiciously like #334 to me, which should be fixed. So need to concentrate here on the postgresql error.

**Comment by brianmay** [comment] 2016-01-06 00:34
@sathoro What queries are we talking about here? There a lot of queries made by this function, and I still don't really know which one is causing the problem.

A full stack trace of the postgresql error would be really useful.

**Comment by brianmay** [comment] 2016-01-06 00:51
So I am guessing the problem comes from this line:

```
q = Q(pk__in=user_obj_perms_queryset.values(fields[0]))
```

Which I believe becomes:

```
q = Q(pk__in=user_obj_perms_queryset.values("object_pk"))
```

Which in turn becomes:

```
q = Q(pk__in=['1', '2', ...])
```

Where it seems that mysql can cope with this, but postgresql can't.

Does this sound right?

**Comment by brianmay** [comment] 2016-01-06 01:02
7 of the built in tests fail if you use postgresql as opposed to the default - sqlite.

```
Creating test database for alias 'default'...
...............................s.............................................................EE...EE........E....EE...........................................................................................................
======================================================================
ERROR: test_any_of_multiple_perms_to_check (guardian.testapp.tests.test_shortcuts.GetObjectsForUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/tree/debian/upstream/django-guardian/guardian/testapp/tests/test_shortcuts.py", line 560, in test_any_of_multiple_perms_to_check
    self.assertEqual(len(objects), 2)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: operator does not exist: integer = character varying
LINE 1: ..."name" FROM "auth_group" WHERE ("auth_group"."id" IN (SELECT...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


======================================================================
ERROR: test_empty_perms_sequence (guardian.testapp.tests.test_shortcuts.GetObjectsForUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/tree/debian/upstream/django-guardian/guardian/testapp/tests/test_shortcuts.py", line 474, in test_empty_perms_sequence
    set(objects),
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: operator does not exist: integer = character varying
LINE 1: ..."name" FROM "auth_group" WHERE ("auth_group"."id" IN (SELECT...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


======================================================================
ERROR: test_has_any_permissions (guardian.testapp.tests.test_shortcuts.GetObjectsForUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/tree/debian/upstream/django-guardian/guardian/testapp/tests/test_shortcuts.py", line 777, in test_has_any_permissions
    self.assertEqual(len(objects), len(groups))
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: operator does not exist: integer = character varying
LINE 1: ..."name" FROM "auth_group" WHERE ("auth_group"."id" IN (SELECT...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


======================================================================
ERROR: test_has_global_permission_and_object_based_permission (guardian.testapp.tests.test_shortcuts.GetObjectsForUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/tree/debian/upstream/django-guardian/guardian/testapp/tests/test_shortcuts.py", line 628, in test_has_global_permission_and_object_based_permission
    self.assertEqual(set(objects.values_list('name', flat=True)),
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 1217, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 794, in results_iter
    results = self.execute_sql(MULTI)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: operator does not exist: integer = character varying
LINE 1: ..."name" FROM "auth_group" WHERE ("auth_group"."id" IN (SELECT...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


======================================================================
ERROR: test_multiple_perms_to_check_no_groups (guardian.testapp.tests.test_shortcuts.GetObjectsForUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/tree/debian/upstream/django-guardian/guardian/testapp/tests/test_shortcuts.py", line 546, in test_multiple_perms_to_check_no_groups
    self.assertEqual(len(objects), 1)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: operator does not exist: integer = character varying
LINE 1: ...."name" FROM "auth_group" WHERE "auth_group"."id" IN (SELECT...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


======================================================================
ERROR: test_object_based_permission_with_groups_2perms (guardian.testapp.tests.test_shortcuts.GetObjectsForUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/tree/debian/upstream/django-guardian/guardian/testapp/tests/test_shortcuts.py", line 680, in test_object_based_permission_with_groups_2perms
    set(objects.values_list('id', flat=True)),
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 1217, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 794, in results_iter
    results = self.execute_sql(MULTI)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: operator does not exist: integer = character varying
LINE 1: ...o_content_type" WHERE ("django_content_type"."id" IN (SELECT...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


======================================================================
ERROR: test_object_based_permission_with_groups_3perms (guardian.testapp.tests.test_shortcuts.GetObjectsForUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/tree/debian/upstream/django-guardian/guardian/testapp/tests/test_shortcuts.py", line 709, in test_object_based_permission_with_groups_3perms
    set(objects.values_list('id', flat=True)),
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 1217, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 794, in results_iter
    results = self.execute_sql(MULTI)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: operator does not exist: integer = character varying
LINE 1: ...o_content_type" WHERE ("django_content_type"."id" IN (SELECT...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


----------------------------------------------------------------------
Ran 222 tests in 4.845s

FAILED (errors=7, skipped=1)
Destroying test database for alias 'default'...
```

**Comment by brianmay** [comment] 2016-01-06 01:07
For the record, all the tests pass with mysql as well as sqlite.

**Comment by brianmay** [comment] 2016-01-06 01:32
Here is an example of a SQL query that fails. Not sure I understand yet how this gets generated.

```
SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" WHERE ("auth_group"."id" IN (SELECT U0."object_pk" FROM "guardian_userobjectpermission" U0 INNER JOIN "auth_permission" U2 ON ( U0."permission_id" = U2."id" ) WHERE (U0."user_id" = 1 AND U2."content_type_id" = 2 AND U2."codename" IN (change_group, delete_group))) OR "auth_group"."id" IN (SELECT U0."object_pk" FROM "guardian_groupobjectpermission" U0 INNER JOIN "auth_group" U1 ON ( U0."group_id" = U1."id" ) INNER JOIN "testapp_customuser_groups" U2 ON ( U1."id" = U2."group_id" ) INNER JOIN "auth_permission" U4 ON ( U0."permission_id" = U4."id" ) WHERE (U2."customuser_id" = 1 AND U4."codename" IN (change_group, delete_group) AND U4."content_type_id" = 2)))
```

**Comment by brianmay** [comment] 2016-01-06 01:43
The code I documented above seems wrong, we don't get a list as I mentioned above, but a list of dictionarys. Not sure this is valid parameter for `pk__in`. Out of time now, will look at this later.

**Comment by brianmay** [comment] 2016-01-06 03:38
All tests pass for me under Postgresql with the following change:

```
diff --git a/guardian/shortcuts.py b/guardian/shortcuts.py
index d064f14..feefedb 100644
--- a/guardian/shortcuts.py
+++ b/guardian/shortcuts.py
@@ -515,9 +515,18 @@ def get_objects_for_user(user, perms, klass=None, use_groups=True, any_perm=Fals
         counts = user_obj_perms_queryset.values(fields[0]).annotate(object_pk_count=Count(fields[0]))
         user_obj_perms_queryset = counts.filter(object_pk_count__gte=len(codenames))
 
-    q = Q(pk__in=user_obj_perms_queryset.values(fields[0]))
+    values = user_obj_perms_queryset.values(fields[0])
+    if len(values) == 0:
+        return queryset.none()
+
+    values = [v['object_pk'] for v in values]
+    q = Q(pk__in=values)
     if use_groups:
-        q |= Q(pk__in=groups_obj_perms_queryset.values(fields[0]))
+        values = groups_obj_perms_queryset.values(fields[0])
+        if len(values) == 0:
+            return queryset.none()
+        values = [v['object_pk'] for v in values]
+        q |= Q(pk__in=values)
 
     return queryset.filter(q)
```

**Comment by brianmay** [comment] 2016-01-06 03:51
Oh, I see. The query actually returns a `ValuesQuerySet` (not a list of dictionaries), which is valid for `pk__in` and triggers the postgresql table join. My code above bypasses this table join by forcing it to load in the pks first.

Think I am starting to understand the problem now.

**Comment by brianmay** [comment] 2016-01-06 06:50
The travis tests have been changed to highlight this failure now. They also highlight another unrelated mysql failure too :-(

I filled a bug report at Django, will be interesting to see what if any feedback we get:
https://code.djangoproject.com/ticket/26042

**Comment by mitar** [comment] 2016-01-06 15:08
@kostko: Why this works for us with PostgreSQL then? Because we are using UUIDs for primary keys?

**Comment by mitar** [comment] 2016-01-06 15:11
> Oh, I see. The query actually returns a ValuesQuerySet (not a list of dictionaries), which is valid for pk__in and triggers the postgresql table join. My code above bypasses this table join by forcing it to load in the pks first.

Yes, the point of that change was to leave to the SQL engine to make a join (or subquery) instead of reading values into the Python and then making one more query back to SQL with what you read before.

We do use PostgreSQL (for where we had [something similar in use for some time now](https://github.com/wlanslovenija/nodewatcher/blob/development/nodewatcher/utils/permissions.py#L224)), so I am surprised that we are finding issues with PostgreSQL here.

**Comment by mitar** [comment] 2016-01-06 15:21
Which exactly primary key types are failing now? Ints? UUIDs?

**Comment by tomka** [comment] 2016-01-06 16:33
For us it is failing with integer keys in Postgres.

**Comment by mitar** [comment] 2016-01-06 18:42
Which version of PostgreSQL do you have?

**Comment by tomka** [comment] 2016-01-06 19:19
I tested 9.3 and 9.4, in both the query fails.

**Comment by sathoro** [comment] 2016-01-06 19:29
To add to the above, it fails for me using int pks in 9.4.4 and 9.4.5.

It would be interesting to do a performance test to see the difference between the join and two separate queries.

**Comment by brianmay** [comment] 2016-01-06 21:34
For details of the error see https://travis-ci.org/django-guardian/django-guardian/jobs/100537654; this particular case was for Python 3.5 and Django 1.9.1, however it happens for other combinations. The stack trace is slightly misleading, as it occurs when the query gets used, not when the query gets constructed.

I am starting to suspect we might have to separate the query into two again. I suspect the performance impact (in terms of memory used not just extra time) will depend on how many results the first query generates.

Upstream Django closed my bug report saying it is a duplicate of https://code.djangoproject.com/ticket/16055.

**Comment by mitar** [comment] 2016-01-06 21:42
So, this is strange. For us it works when you do in PostgreSQL:

```
SELECT 1 IN ('1', '2');
SELECT '1' IN (1, 2);
```

But not when:

```
SELECT 1 IN ('1'::text, '2'::text);
SELECT '1'::text IN (1, 2);
```

So conversion between ints and varchars work well. But conversion between ints and text does not. But who would want to have text-based primary keys?

If you create and implicit cast `CREATE CAST (integer AS text) WITH INOUT AS IMPLICIT` then even the latter works.

So the question is, are we sure we are using varchars and not text for generic index?

**Comment by brianmay** [comment] 2016-01-06 21:51
The Django migration code to create the table is as follows:

```
# DATABASE_URL=postgres://brian@/test ./manage.py sqlmigrate guardian 0001_initial
BEGIN;
CREATE TABLE "guardian_groupobjectpermission" ("id" serial NOT NULL PRIMARY KEY, "object_pk" varchar(255) NOT NULL, "content_type_id" integer NOT NULL, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
CREATE TABLE "guardian_userobjectpermission" ("id" serial NOT NULL PRIMARY KEY, "object_pk" varchar(255) NOT NULL, "content_type_id" integer NOT NULL, "permission_id" integer NOT NULL, "user_id" integer NOT NULL);
...
```

If I got the right table, looks like varchar to me...

**Comment by brianmay** [comment] 2016-01-07 23:32
Current status: I believe this is a Django bug. However the bug has been opened 5 years ago, and there doesn't seem to be much progress, except for the addition of a test case.

I am inclined to partially revert the offending commit, just so we can fix the breakage.

```
diff --git a/guardian/shortcuts.py b/guardian/shortcuts.py
index d064f14..c082c36 100644
--- a/guardian/shortcuts.py
+++ b/guardian/shortcuts.py
@@ -515,11 +515,17 @@ def get_objects_for_user(user, perms, klass=None, use_groups=True, any_perm=Fals
         counts = user_obj_perms_queryset.values(fields[0]).annotate(object_pk_count=Count(fields[0]))
         user_obj_perms_queryset = counts.filter(object_pk_count__gte=len(codenames))
 
-    q = Q(pk__in=user_obj_perms_queryset.values(fields[0]))
+    values = user_obj_perms_queryset.values_list(fields[0], flat=True)
+    if user_model.objects.is_generic():
+        values = list(values)
+    objects = queryset.filter(pk__in=values)
     if use_groups:
-        q |= Q(pk__in=groups_obj_perms_queryset.values(fields[0]))
+        values = groups_obj_perms_queryset.values_list(fields[0], flat=True)
+        if group_model.objects.is_generic():
+            values = list(values)
+        objects |= queryset.filter(pk__in=values)
 
-    return queryset.filter(q)
+    return objects
 
 
 def get_objects_for_group(group, perms, klass=None, any_perm=False, accept_global_perms=True):
```

(note in the above code objects is actually a queryset)

**Comment by mitar** [comment] 2016-01-08 00:47
Could this maybe be some function call argument which would use one or the other code path? Because for us it works, so I am really unsure why.

**Comment by tomka** [comment] 2016-01-08 03:45
Until a better solution is found, I feel reverting this commit might be the right call.

> Could this maybe be some function call argument 

Well, like I said above it works for me if `accept_global_perms=False` in the `get_objects_for_group()` call.

**Closed** 2016-01-08 07:43 UTC

**Comment by ad-m** [comment] 2016-01-08 08:33
Why not provide settings to switch on/off subqueries? We can wrote in docs
to don't use real subqueries in backend like PostgreSQL due bug. I use
MySQL backend, so real subqueries can be useful for me.

I believe real subqueries should be opt-in by settings.

Wysłano z urządzenia mobilnego.
8 sty 2016 08:43 "Brian May" <notifications@github.com> napisał(a):

**Comment by sathoro** [comment] 2016-01-08 08:56
>  I use MySQL backend, so real subqueries can be useful for me.

Why is that, is it a performance reason, have you profiled them?

**Comment by mitar** [comment] 2016-01-08 11:24
+1 for opt-in, or even auto-detection of the backend.
