### ISSUE TITLE
Optionally disable has_perm cache

### ISSUE THREAD

**Issue by scholtalbers** [django-guardian/django-guardian#360] opened 2015-11-06 15:17 UTC
Setting global permissions looks confusing due to the 'caching'.

    In [16]: u = User.objects.last()
    In [17]: assign_perm('blog.view_post', u)
    Out[17]: <Permission: blog | post | Can view post>
    In [18]: u.has_perm('blog.view_post')
    Out[18]: False
    In [19]: u = User.objects.last()
    In [20]: u.has_perm('blog.view_post')
    Out[20]: True

**Comment by lukaszb** [comment] 2015-11-06 15:31
That's documented "feature" and how package was designed. I don't see real use cases where one would want to use same User object in a long-running process for checking permissions. Am closing for now, however, please feel free and let me know if there is a real use case agains this behaviour.

**Closed by lukaszb** 2015-11-06 15:31 UTC

**Comment by rudolfolah** [comment] 2020-01-22 12:47
Thanks for documenting this feature, though I encountered one real use case: tests.

I have a test where I call `has_perm` *before* I add a user to a group and then again afterwards to ensure the permission is set correctly:

```python
self.assertFalse(self.user.has_perm('my_app.change_mymodel', self.mymodel_instance))
self.user.groups.add(Group.objects.get(name='group_with_change_permission')
self.assertTrue(self.user.has_perm('my_app.change_mymodel', self.mymodel_instance))
```

Due to the caching within the `user.has_perm` method, the 2nd assertion will fail.

**Comment by lukaszb** [comment] 2020-01-22 12:52
@rudolfolah at tests you can simply refetch user object from the database.
