### ISSUE TITLE
objectpk is incorrect when trying to modify object permissions in admin Django 1.9

### ISSUE THREAD

**Issue by jlark** [django-guardian/django-guardian#377] opened 2015-12-21 09:28 UTC
I recently updated to Django 1.9 and notice that when I try to view the permissions on an object the incorrect pk is taken from the URL. 

I've gone ahead and fixed the code locally. Happy to send a pull request if you think it's adequate.

```python
            if django.VERSION == (1,9):
                myurls = patterns('',
                    #adding in /change/ to URL pattern to Django 1.9
                    url(r'^(?P<object_pk>.+)/change/permissions/$',
                        view=self.admin_site.admin_view(self.obj_perms_manage_view),
                        name='%s_%s_permissions' % info),
                    url(r'^(?P<object_pk>.+)/permissions/user-manage/(?P<user_id>\-?\d+)/$',
                        view=self.admin_site.admin_view(
                            self.obj_perms_manage_user_view),
                        name='%s_%s_permissions_manage_user' % info),
                    url(r'^(?P<object_pk>.+)/permissions/group-manage/(?P<group_id>\-?\d+)/$',
                        view=self.admin_site.admin_view(
                            self.obj_perms_manage_group_view),
                        name='%s_%s_permissions_manage_group' % info),
                )
            else:
                myurls = patterns('',
                    url(r'^(?P<object_pk>.+)/permissions/$',
                        view=self.admin_site.admin_view(self.obj_perms_manage_view),
                        name='%s_%s_permissions' % info),
                    url(r'^(?P<object_pk>.+)/permissions/user-manage/(?P<user_id>\-?\d+)/$',
                        view=self.admin_site.admin_view(
                            self.obj_perms_manage_user_view),
                        name='%s_%s_permissions_manage_user' % info),
                    url(r'^(?P<object_pk>.+)/permissions/group-manage/(?P<group_id>\-?\d+)/$',
                        view=self.admin_site.admin_view(
                            self.obj_perms_manage_group_view),
                        name='%s_%s_permissions_manage_group' % info),
                )
```

**Comment by brianmay** [comment] 2015-12-21 09:54
I suspect you might be referring to an issue that has already been fixed in the latest git develop branch.

The urls are fine; the problem is the link generated was broken. This is now fixed.

**Comment by jlark** [comment] 2015-12-21 10:14
That might be the case. If fixed please ignore. Thank you!

Alp

On Mon, Dec 21, 2015 at 11:54 AM, Brian May <notifications@github.com>
wrote:

> I suspect you might be referring to an issue that has already been fixed
> in the latest git develop branch.
>
> The urls are fine; the problem is the link generated was broken. This is
> now fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-guardian/django-guardian/issues/377#issuecomment-166254274>
> .
>



-- 
Alp
www.atilev.com

**Closed** 2015-12-22 05:54 UTC
