### ISSUE TITLE
Installation uninstalls existing Django version and installs 1.9.5

### ISSUE THREAD

**Issue by holyoaks** [django-guardian/django-guardian#420] opened 2016-04-05 17:14 UTC
pip install django-guardian downloads the .whl file and that seems to be set to django == 1.9.5, instead of django >= "minimum django version supported". We have not migrated to Django 1.9 yet, and so we have to install django-guardian, then uninstall django 1.9.5, and then reinstall django 1.8.12. Minor issue, but annoying

**Comment by brianmay** [comment] 2016-04-05 21:56
I have no idea why setuptools might be doing this, as django-guardian lists the requirement as "Django >= 1.7" - there is no mention anywhere inside django-guardian of Django 1.9.5. Can you please copy the full output here?

**Comment by brianmay** [comment] 2016-04-05 21:58
Is it possible that pip install was installing another package at the time that required Django 1.9.5?

**Comment by ad-m** [comment] 2016-04-05 22:04
For me django-guardian works fine.

````
$ virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in venv/bin/python2
Also creating executable in venv/bin/python
Installing setuptools, pip...done.
$ source venv/bin/activate
(venv)$ pip install "django==1.7.5"
Downloading/unpacking django==1.7.5
  Downloading Django-1.7.5-py2.py3-none-any.whl (7.4MB): 7.4MB downloaded
Installing collected packages: django
Successfully installed django
Cleaning up...
(venv)adas@adas-Latitude-E7450:/tmp/aa$ pip install django-guardian
Downloading/unpacking django-guardian
  Downloading django-guardian-1.4.4.tar.gz (145kB): 145kB downloaded
  Running setup.py (path:/tmp/pip-build-hEyzEi/django-guardian/setup.py) egg_info for package django-guardian
    
    Installed /tmp/easy_install-Y5UZ1h/pytest-runner-2.7.1/.eggs/setuptools_scm-1.10.1-py2.7.egg
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-build-hEyzEi/django-guardian/.eggs/pytest_runner-2.7.1-py2.7.egg
    Searching for setuptools-scm
    Reading https://pypi.python.org/simple/setuptools_scm/
    Best match: setuptools-scm 1.10.1
    Downloading https://pypi.python.org/packages/source/s/setuptools_scm/setuptools_scm-1.10.1.zip#md5=63f2dd6c1f087ff1a2c74a5cf11e988a
    Processing setuptools_scm-1.10.1.zip
    Writing /tmp/easy_install-IWo0EB/setuptools_scm-1.10.1/setup.cfg
    Running setuptools_scm-1.10.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-IWo0EB/setuptools_scm-1.10.1/egg-dist-tmp-cVyWsW
    Moving setuptools_scm-1.10.1-py2.7.egg to /tmp/pip-build-hEyzEi/django-guardian/.eggs
    
    Installed /tmp/pip-build-hEyzEi/django-guardian/.eggs/setuptools_scm-1.10.1-py2.7.egg
    
    warning: no files found matching '*.json' under directory 'guardian/fixtures'
    warning: no files found matching '*.html' under directory 'guardian/tests/templates'
    warning: no files found matching '*.conf' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.eot' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
    warning: no files found matching '*.rb' under directory 'docs'
    warning: no files found matching '*.sass' under directory 'docs'
    warning: no files found matching '*.svg' under directory 'docs'
    warning: no files found matching '*.ttf' under directory 'docs'
    warning: no files found matching '*.woff' under directory 'docs'
    warning: no previously-included files matching '*' found under directory 'docs/build'
Requirement already satisfied (use --upgrade to upgrade): Django>=1.7 in ./venv/lib/python2.7/site-packages (from django-guardian)
Downloading/unpacking six (from django-guardian)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: django-guardian, six
  Running setup.py install for django-guardian
    
    warning: no files found matching '*.json' under directory 'guardian/fixtures'
    warning: no files found matching '*.html' under directory 'guardian/tests/templates'
    warning: no files found matching '*.conf' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.eot' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
    warning: no files found matching '*.rb' under directory 'docs'
    warning: no files found matching '*.sass' under directory 'docs'
    warning: no files found matching '*.svg' under directory 'docs'
    warning: no files found matching '*.ttf' under directory 'docs'
    warning: no files found matching '*.woff' under directory 'docs'
    warning: no previously-included files matching '*' found under directory 'docs/build'
Successfully installed django-guardian six
Cleaning up...
(venv)$ pip freeze | egrep '[dD]jango'
Django==1.7.5
django-guardian==1.4.4
```

**Comment by ad-m** [comment] 2016-04-05 22:14
One more test.
```
$ for i in {1.4.1,1.4.0,1.3.2,1.3.1,1.3}; do pip install django-guardian=="$i" >>/dev/null; echo "== django-guardian==$i"; pip freeze | grep "Django"; done;
== django-guardian==1.4.1
Django==1.7.5
== django-guardian==1.4.0
Django==1.7.5
== django-guardian==1.3.2
Django==1.7.5
== django-guardian==1.3.1
Django==1.7.5
== django-guardian==1.3
Django==1.7.5
```

**Comment by pydanny** [comment] 2016-04-15 17:26
django-guardian works fine on our Django 1.8 projects, never force installing Django 1.9.5. I think it is another package causing the problem.

**Comment by brianmay** [comment] 2016-04-16 06:09
Can't reproduce, I am am going to close this.

**Closed by brianmay** 2016-04-16 06:09 UTC
Labels: moreinfo
