### ISSUE TITLE
PermissionRequiredMixin  not support UpdateView   DeleteView,DetailView  CreateView

### ISSUE THREAD

**Issue by iloveyo123u1** [django-guardian/django-guardian#291] opened 2015-01-17 03:59 UTC
hi,
i have 2 question:

Q1. UpdateView
this my code

# views.py

class xoUpdate(PermissionRequiredMixin,UpdateView):
    permission_required="xo.change_xo1"
    login_url="/"  
    model=xo
    success_url=reverse_lazy("xoList")

When I visit to edit records the url 【http://192.168.145.10:8000/xo/update/1】, he returned to the home page 【http://192.168.145.10:8000/】

-------*****************************---------

Q2：CreateView

like this https://github.com/lukaszb/django-guardian/issues/279

i defining a 
get_object(self): 
    return None

CreateView it work

----------------***********--

 
it not support DeleteView,DetailView，  like UpdateView

thank you very much

**Comment by iloveyo123u1** [comment] 2015-01-17 21:55
ok,  it work,
this is my change code:

https://github.com/iloveyo123u1/django-guardian/commit/4e04fa039db2507efc76f550460438ca94fd0713#diff-e9408a9eb5e27ae887d21b9843d54698

**Comment by aidanlister** [comment] 2015-02-15 22:14
Do all the tests pass?

**Comment by myth** [comment] 2015-10-31 14:25
I am experiencing the same issue with the PermissionRequiredMixin accompanied by an UpdateView. Overriding the `get_object()` to return None is not an option, as it is required by the ModelForm / SingleObjectMixin. Has there been any more research into an actual solution to the problem and not a temporary workaround? It is related to #279

**Comment by aidanlister** [comment] 2015-11-01 00:39
You should not use get_object() => None for UpdateView .. only CreateView.

**Comment by myth** [comment] 2015-11-01 01:01
I am aware of that. That's why i'm asking if there has been any progress regarding UpdateView.

**Comment by aidanlister** [comment] 2015-11-01 01:26
There's nothing wrong with UpdateView is there?

**Comment by myth** [comment] 2015-11-01 01:36
In my project I am combining a PermissionRequiredMixin with an UpdateView, and it always returns with a 403. I am using the mixin on all my other views (ListView, DetailView, TemplateView) and it works fine. However, for UpdateView, i get access denied no matter what `permission_required` value i set.

The only thing that works is to enable `accept_global_perms`, but that defeats the purpose of having object-level permissions.

**Comment by myth** [comment] 2015-11-01 01:41
Nevermind, i re-read the documentation for the decorator. It was the missing accept_global_perms that was the issue, as the particular user had group assigned model permissions.

**Comment by brianmay** [comment] 2016-02-22 06:57
Suspect this is a duplicate of #146, so closing.

**Closed by brianmay** 2016-02-22 06:57 UTC

**Comment by ad-m** [comment] 2016-08-16 22:39
Fixed. See #448, #433.
