### ISSUE TITLE
Type Error changing instance permission for object from admin in mysql

### ISSUE THREAD

**Issue by caupetit** [django-guardian/django-guardian#394] opened 2016-02-08 16:46 UTC
Hello.

Got a bug with mariadb (django mysql) that i do not got under postgresql

i'm using django 1.9, guardian 1.4.1

i got a model:
```

class Document(TranslatableModel):
    category = models.ForeignKey(DocumentCategory)

    translations = TranslatedFields(
            name=models.CharField(max_length=100, null=True),
            description=models.CharField(max_length=255, null=True, blank=True),
            file=models.FileField(null=True, blank=True)
    )

    class Meta:
        permissions = (
            ('view_document', 'Can view document'),
        )

    def get_best_traduction(self):
        traduction = self.lazy_translation_getter('name', str(self.pk))
        if not traduction:
            return None
        return self

    def __str__(self):
        return self.lazy_translation_getter('name', str(self.pk)) or self.__class__.__name__ + str(self.pk)

    def __unicode__(self):
        return self.__str__()
```

I'm trying to set 'view_permission' and no other one (add etc) for a group to an instance of Document from admin panel.

under postgres all ok but swithing to mariadb i got this:

```
TypeError at /fr/admin/dispenser/document/2/permissions/group-manage/2/
unsupported operand type(s) for +=: 'int' and 'NoneType'
Request Method:	POST
Request URL:	http://127.0.0.1:8082/fr/admin/dispenser/document/2/permissions/group-manage/2/
Django Version:	1.9
Exception Type:	TypeError
Exception Value:	
unsupported operand type(s) for +=: 'int' and 'NoneType'
Exception Location:	/home/online-dev/shared/app/env/lib/python2.7/site-packages/django/db/models/deletion.py in delete, line 293
Python Executable:	/home/online-dev/shared/app/env/bin/python
Python Version:	2.7.10
Python Path:	
['/home/online-dev/shared/app/src',
 '/home/online-dev/shared/app/env/lib/python27.zip',
 '/home/online-dev/shared/app/env/lib/python2.7',
 '/home/online-dev/shared/app/env/lib/python2.7/plat-linux2',
 '/home/online-dev/shared/app/env/lib/python2.7/lib-tk',
 '/home/online-dev/shared/app/env/lib/python2.7/lib-old',
 '/home/online-dev/shared/app/env/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/home/online-dev/shared/app/env/lib/python2.7/site-packages']
Server time:	lun, 8 Fév 2016 15:49:48 +0000
Traceback Switch to copy-and-paste view

/home/online-dev/shared/app/env/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
                    response = self.process_exception_by_middleware(e, request) ...
/home/online-dev/shared/app/env/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
                    response = wrapped_callback(request, *callback_args, **callback_kwargs) ...

/home/online-dev/shared/app/env/lib/python2.7/site-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, *args, **kwargs) ...

/home/online-dev/shared/app/env/lib/python2.7/site-packages/django/views/decorators/cache.py in _wrapped_view_func
        response = view_func(request, *args, **kwargs) ...

/home/online-dev/shared/app/env/lib/python2.7/site-packages/django/contrib/admin/sites.py in inner
            return view(request, *args, **kwargs) ...

/home/online-dev/shared/app/env/lib/python2.7/site-packages/guardian/admin.py in obj_perms_manage_group_view
            form.save_obj_perms() ...

/home/online-dev/shared/app/env/lib/python2.7/site-packages/guardian/forms.py in save_obj_perms
            remove_perm(perm, self.group, self.obj) ...

/home/online-dev/shared/app/env/lib/python2.7/site-packages/guardian/shortcuts.py in remove_perm
        model.objects.remove_perm(perm, group, obj) ...

/home/online-dev/shared/app/env/lib/python2.7/site-packages/guardian/managers.py in remove_perm
        self.filter(**filters).delete() ...

/home/online-dev/shared/app/env/lib/python2.7/site-packages/django/db/models/query.py in delete
        deleted, _rows_count = collector.delete() ...

/home/online-dev/shared/app/env/lib/python2.7/site-packages/django/db/models/deletion.py in delete
                deleted_counter[qs.model._meta.label] += count ...
```

I could fix it by changing:

```
guardian/forms.py 

line 186:
model_perms = [c[0] for c in self.get_obj_perms_field_choices()]
to :
model_perms = [c[0] for c in self.get_obj_perms_field_initial()]
```

i think it come from trying to delete global object permissions for group instead of current instance permissions, but can't figure out why all works with postgres.

If this is an issue and not a mistake from me, same thing happens for user permission (line 139)

**Comment by brianmay** [comment] 2016-02-09 03:05
I have tried to write a test case to reproduce this failure, however so far not been able to see any failures :-(

What version of Django 1.9.x where you using?

**Comment by brianmay** [comment] 2016-02-09 03:13
Correction: Looks like I can reproduce with Django 1.9.0. Just like in your case it only happens for mysql, not sqllite or postgresql.

However, cannot reproduce with Django 1.9.1 or Django 1.9.2 - so I am guessing this is a Django bug that has already been fixed...

**Comment by caupetit** [comment] 2016-02-09 08:24
You'r right, Same for me, all ok with django 1.9.2. (i was using 1.9.0) my bad, thanks for quick answer !

**Comment by brianmay** [comment] 2016-02-11 00:14
Thanks for confirming. Closing.

**Closed by brianmay** 2016-02-11 00:14 UTC
Labels: moreinfo
