### ISSUE TITLE
Django 1.9 admin URLs incompatible

### ISSUE THREAD

**Issue by adontz** [django-guardian/django-guardian#381] opened 2015-12-29 18:14 UTC
Since Django 1.9 object modification form in admin interface is located under /{PK}/change/ URL, and django-guardian do not expect this. So (line 100+ in admin.py) the following code

        urls = super(GuardedModelAdminMixin, self).get_urls()
        if self.include_object_permissions_urls:
            info = self.model._meta.app_label, get_model_name(self.model)
            myurls = patterns('',
                url(r'^(?P<object_pk>.+)/permissions/$',
                    view=self.admin_site.admin_view(self.obj_perms_manage_view),
                    name='%s_%s_permissions' % info),
                url(r'^(?P<object_pk>.+)/permissions/user-manage/(?P<user_id>\-?\d+)/$',
                    view=self.admin_site.admin_view(
                        self.obj_perms_manage_user_view),
                    name='%s_%s_permissions_manage_user' % info),
                url(r'^(?P<object_pk>.+)/permissions/group-manage/(?P<group_id>\-?\d+)/$',
                    view=self.admin_site.admin_view(
                        self.obj_perms_manage_group_view),
                    name='%s_%s_permissions_manage_group' % info),
            )
            urls = myurls + urls
        return urls

causes URL to to be parsed incorrectly, so that object_pk parameter is equal to {PK}/change and not {PK} and we get ValueError at line 156
 
       obj = get_object_or_404(self.get_queryset(request), pk=unquote(object_pk))

 what to do is described in release notes https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#admin-reverse-urls

**Comment by brianmay** [comment] 2016-01-05 07:36
I suspect this issue has already been resolved in git master; however I will leave it open for now as a number people have reported it.

**Comment by iwootten** [comment] 2016-01-07 14:44
git master appears to be the currently released version, 1.3.2 - with which I'm also currently experiencing this issue. Appears to be fixed in dev (assume you meant that branch @brianmay?), although travis is currently complaining.

**Comment by brianmay** [comment] 2016-01-07 22:11
Oh, yes, sorry. Meant the devel branch.

Travis is complaining about #366; this was broken is 1.3.2 too; however the tests in 1.3.2 didn't test Postgres and as this is a Postgres specific problem it didn't get detected. I want to fix this before making a new release.

**Comment by brianmay** [comment] 2016-01-08 07:54
Just to provide more concrete references, I believe this is a duplicate of #376, and fixed by 9818331aa34bea625eeec9424b9998b2b260f234.

**Comment by brianmay** [comment] 2016-01-08 08:16
Just released 1.4.0, so closing this.

**Closed by brianmay** 2016-01-08 08:16 UTC
