### ISSUE TITLE
Trouble with django-guardian.readthedocs

### ISSUE THREAD

**Issue by dmitryTsatsarin** [django-guardian/django-guardian#398] opened 2016-02-18 08:57 UTC
Trouble with readthedocs
http://dl.dropbox.com/u/13258686/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_028.png

**Comment by brianmay** [comment] 2016-02-18 09:55
Duplicate of #397.

**Closed** 2016-02-21 01:14 UTC
