### ISSUE TITLE
get_obj_perms_model doesn't work, will never return direct foreign key models

### ISSUE THREAD

**Issue by mcgeeco** [django-guardian/django-guardian#344] opened 2015-09-01 16:44 UTC
In [this code](https://github.com/django-guardian/django-guardian/blob/devel/guardian/utils.py#L153), the following line is wrong:

```python
        model = getattr(attr, 'model', None)
```

It returns the model to which the permissions are assigned. To return what it's supposed to, it should be:
```python
        model = getattr(attr, 'related_model', None)
```

Because of this, assign_perm won't find any direct foreign key models. I feel like I might be missing something, as I can't see this issue logged anywhere else and I thought it would have been noticed by now - so sorry if I'm wrong.
I can try and put in a pull request for this tomorrow if needed, as I'd say it's pretty critical. There must be a test or two missing also if it wasn't picked up?

**Comment by ad-m** [comment] 2015-09-01 16:47
Duplicate of #337 and #319 .

**Comment by mcgeeco** [comment] 2015-09-01 16:49
Ah sorry, the titles were hard to connect. Thanks!

**Closed** 2015-09-01 16:49 UTC
