### ISSUE TITLE
Queryset exception Django 1.8

### ISSUE THREAD

**Issue by tyler274** [django-guardian/django-guardian#315] opened 2015-05-01 14:30 UTC
object has no attribute 'queryset'

guardian/admin.py" in obj_perms_manage_view
  151.         obj = get_object_or_404(self.queryset(request), pk=object_pk)

**Comment by Hedde** [comment] 2015-05-09 14:03
django-guardian/guardian/admin.py in get_queryset

    def get_queryset(self, request):
        # Prefer the Django >= 1.6 interface but maintain
        # backward compatibility
        method = getattr(
            super(GuardedModelAdminMixin, self), 'get_queryset',
            getattr(super(GuardedModelAdminMixin, self), 'queryset'))
        qs = method(request)

The queryset param has been removed after deprecation, for backwards compatibilty the check should be altered, e.g.

        # Prefer the Django >= 1.6 interface but maintain
        # backward compatibility
        try:
            method = getattr(
                super(GuardedModelAdminMixin, self), 'get_queryset'
            )
        except AttributeError:  # Django <= 1.6
            method = getattr(
                super(GuardedModelAdminMixin, self).queryset
            )

**Comment by HEdingfield** [comment] 2015-05-09 18:59
I believe this is a duplicate of #307.

**Comment by thedrow** [comment] 2015-06-17 14:45
@lukaszb Was this resolved? It is in 1.3? Can we close it?

**Comment by dgabrielson** [comment] 2015-06-17 19:04
In django-guardian 1.3 from PyPi; this line is still:
 obj = get_object_or_404(self.queryset(request), pk=object_pk)

**Comment by 7wonders** [comment] 2015-07-01 16:53
Apply same principle as the get_queryset??

'''
        method = getattr(
            super(GuardedModelAdminMixin, self), 'get_queryset',
            getattr(super(GuardedModelAdminMixin, self), 'queryset', None))
        obj = get_object_or_404(method(request), pk=object_pk)
'''

**Comment by cabello** [comment] 2015-09-01 21:14
#307 fixes this.

**Comment by brianmay** [comment] 2015-11-12 21:38
#336 was merged; closing.

**Closed by brianmay** 2015-11-12 21:38 UTC
