### ISSUE TITLE
Way to exclude guardian from apps.

### ISSUE THREAD

**Issue by SzateX** [django-guardian/django-guardian#658] opened 2019-11-14 22:02 UTC
Hi. I'm looking for way to exclude guardian to being used in some apps. 

My Django project has two apps (+ some of builtin or extern). One of them is needed to be on other database, and for them I don't want use guardian (because they don't need to keep permissions). But in migration i got some of errors (https://gist.github.com/SzateX/2c5a6c65c4c3d9bd1e748ee2ba35debc - traceback). 
Is any way to exclude guardian from app?

**Comment by ad-m** [comment] 2019-11-14 22:28
Which version of Django-Guardian do you use?

**Comment by SzateX** [comment] 2019-11-14 22:56
> 
> 
> Which version of Django-Guardian do you use?

I use 2.1.0

**Comment by brianmay** [comment] 2019-11-16 00:18
Why do you think Django-Guardian is the source of these errors? I don't see any reference to guardian in the supplied stack trace. Plus on the command line you explicitly only include migrations from `MQTTApi`. Did I miss something?

**Comment by SzateX** [comment] 2019-11-16 13:56
> 
> 
> Why do you think Django-Guardian is the source of these errors? I don't see any reference to guardian in the supplied stack trace. Plus on the command line you explicitly only include migrations from `MQTTApi`. Did I miss something?

Look for line 38 of stacktrace

**Comment by brianmay** [comment] 2019-11-16 23:01
OK, I understand the error now.

Not sure I understand entirely your use case however. It looks like you don't have the `auth_user` table.

There is no way Django-Guardian will work without a table - referenced by `AUTH_USER_MODEL` to store users in. This should normally be created by the Django migrations.

You say "I don't want use guardian", but to me it looks like you have included Django Guardian in your `INSTALLED_APPS` setting? If so, why?

**Comment by SzateX** [comment] 2019-11-17 14:18
> 
> 
> OK, I understand the error now.
> 
> Not sure I understand entirely your use case however. It looks like you don't have the `auth_user` table.
> 
> There is no way Django-Guardian will work without a table - referenced by `AUTH_USER_MODEL` to store users in. This should normally be created by the Django migrations.
> 
> You say "I don't want use guardian", but to me it looks like you have included Django Guardian in your `INSTALLED_APPS` setting? If so, why?

Okay. I have written two apps. One needed django-guardian, another not - the MQTTApi (which is on seperate database). And for them I have troubles.

**Comment by brianmay** [comment] 2019-11-18 07:41
I still don't quite follow. If MQTTApi doesn't need django-guardian, why is it being installed? Why does the `INSTALLED_APPS` setting for MQTTApi refer to it if it isn't needed?

**Comment by SzateX** [comment] 2019-11-18 11:54
> 
> 
> I still don't quite follow. If MQTTApi doesn't need django-guardian, why is it being installed? Why does the `INSTALLED_APPS` setting for MQTTApi refer to it if it isn't needed?

Because I have two apps in one project.

**Comment by brianmay** [comment] 2019-11-18 20:42
I suspect this is actually a duplicate of #650, which is solved in #651. If so, the key issue that I was missing is that you are using db routing, and multiple databases. Normally multiple apps in one project all share the one database, which is what was confusing me.

**Comment by brianmay** [comment] 2019-11-27 20:50
I just merged #651, so closing this.

**Closed by brianmay** 2019-11-27 20:50 UTC
