### ISSUE TITLE
Having bug in guardian when deployment 

### ISSUE THREAD

**Issue by drayanaindra** [django-guardian/django-guardian#257] opened 2014-08-27 05:12 UTC
Hello, i create API for registration and i have problem when i post data using API.

     AttributeError: 'NoneType' object has no attribute 'objects'

     Exception Location:	/var/envs/project/local/lib/python2.7/site-packages/guardian/models.py in save, line 35

i don't know what must i doing. because in my localhost my API good working and have not error.
can help me ?

**Comment by brianmay** [comment] 2015-11-13 04:01
I am not able to reproduce this issue. With v1.2 from git and Django 1.8.5.

Furthermore, the error message quoted is saying ContentType is None.

Are you still able to reproduce this issue with django-guardian 1.3.1? If so, what version of Django did you use?

**Comment by KasperBrandt** [comment] 2015-11-13 07:45
I think we used Django 1.6.X back then. But we have switched to django-rules for object permissions now.

**Comment by brianmay** [comment] 2015-11-13 08:52
Thanks for your response.

Sounds like it might not be easy to reproduce. I will close this bug report on the assumption that it may have got fixed already - possibly in a later release of Django. Will reopen it if anyone can reproduce the issue.

**Closed by brianmay** 2015-11-13 08:52 UTC
Labels: moreinfo
